# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlutterDemoApp
  # pod 'FlutterAppPod', :git => 'ssh://git@git.sankuai.com/myios/mayaccount.git', :tag => '0.0.1'
  pod 'FlutterAppPod', :path => '../../FlutterAppPod/'
end
